version: '2'

services:
  dokuwiki:
#    image: ianculovici/minimal-dokuwiki:latest
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: "kwzsply"
#    volumes:
#        - ./dokuwiki-data:/dokuwiki
#    restart: always
    ports:
        - "7080:80"

