version: '2'

services:
  dokuwiki:
#    image: ianculovici/minimal-dokuwiki:latest
#    container_name: "mywiki"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
        - ./server/dokuwiki:/dokuwiki:cached
    restart: always
    ports:
        - "7080:80"

